### PR TITLE
data tables for metatypes, metatype relationships

### LINKED ISSUE #89: Modify Taxonomy tables to be Data Tables
## Bug Description

Taxonomy tables with many entries (e.g. Metatype Relationship Pairs) are currently making a single API call to grab all of the rows in the corresponding table. This calls contain a limit, defaulting to 1000. These tables should be updated to act as data tables, grabbing rows with a limit and offset that matches the pagination of the table.

## Steps to Reproduce

Having more than 1000 rows in the Metatype Relationship Pairs table will result in not all of them being visible from the Taxonomies section of the Admin GUI.

## Impact

Does not prevent work from being done.

### LINKED ISSUE #102: Number of Metatype Relationship Pairs limited to 1000
## Bug Description
It seems that the number of Metatype Relationship Pairs is limited to 1000
rels

## Steps to Reproduce
Import a container with the DIAMOND ontology. See number of relationship pairs is 1000. Attempt to add an additional relationship pair, then search in the list

## Impact
Requires reduction of the full ontology

### LINKED ISSUE #117: New Relationship Pair Dialog - Dynamic Search
## Reason
The search boxes for the origin and destination metatypes as well as metatype relationships needs to be dynamic based on user input. Currently it simply lists them and this will max out at 1000 records (as well as bog down the UI)

## Design
Check out the type transformation dialog for examples of metatype and relationship search boxes.

## Impact
Should lower memory footprint and insure all metatypes/metatype relationships are available to a user.

### PR DESCRIPTION
**Pull request by DnOberon**
## Description
Closes #89 
Closes #102 
Closes #117 

Converted the tables for Metatypes, Metatype Relationships, and Metatype Relationship Pairs to dynamic data tables.
Converted search to dynamic search on new Metatype Relationship Pairs
Updated Axios calls
Added `count` into the filter base class
Created and modified filter classes for Metatypes, Metatype Relationships, and Metatype Relationship Pairs
Bugfix for Metatype Keys not converting correctly on update
Modified `.env-sample` with default `CORE_DB_CONNECTION_STRING` - default is the Docker PostgreSQL instance
Corrected issue with HTTP Data Sources not setting active flag correctly.

## Motivation and Context
Needed better listing and CRUD on Metatypes, Metatype Relationships, and Metatype Relationship Pairs.

## How Has This Been Tested?
UI and Test suite

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] My code follows the code style of this project.
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

### CODE REVIEW

File: web_ui/src/api/client.ts [hunk 1]
```diff
@@ -335,7 +337,7 @@ export class Client {
    }
 
 
-   listTypeMappings(containerID: string, dataSourceID: string, {limit, offset, sortBy, sortDesc, resultingMetatypeName, resultingMetatypeRelationshipName, noTransformations}: {limit?: number; offset?: number; sortBy?: string; sortDesc?: boolean; resultingMetatypeName?: string | undefined; resultingMetatypeRelationshipName?: string | undefined; noTransformations?: boolean}): Promise<TypeMappingT[]> {
+   listTypeMappings(containerID: string, dataSourceID: string, {limit, offset, sortBy, sortDesc, resultingMetatypeName, resultingMetatypeRelationshipName }: {limit?: number; offset?: number; sortBy?: string; sortDesc?: boolean; resultingMetatypeName?: string | undefined; resultingMetatypeRelationshipName?: string | undefined; noTransformations?: boolean}): Promise<TypeMappingT[]> {
```
Comment (jerenmb) [inline web_ui/src/api/client.ts:340]: should noTransformations? still be present at the end of this signature?

File: web_ui/src/api/client.ts [hunk 2]
```diff
@@ -151,18 +152,24 @@ export class Client {
...
+      if(count) query.count = "true"
+
+      return this.get<MetatypeRelationshipT[]>(`/containers/${containerID}/metatype_relationships`, query)
    }
 
    createMetatypeRelationship(containerID: string, metatypeRelationship: any): Promise<MetatypeRelationshipT> {
       return this.post<MetatypeRelationshipT>(`/containers/${containerID}/metatype_relationships`, metatypeRelationship)
    }
 
-   retrieveMetatypeRelationship(containerID: string, metatypeRelationshipID: string): Promise<MetatypeRelationshipT> {
```
Comment (jerenmb) [inline web_ui/src/api/client.ts:162]: Reason for removing this?

**Review by jerenmb — APPROVED** [review]
