### PR TITLE
Domain, Repository, Mapper Refactor

### LINKED ISSUE #8: Make migration functionality more robust
Simple as it sounds. Throw some more error switches in there, allow for options of redoing a migration if need be.

### LINKED ISSUE #9: More complex tests on MetatypeKeys, MetatypeRelationshipKeys, and MetatypeRelationshipPairs
We lack solid tests for these data types.

### LINKED ISSUE #10: Stop JWT encrypting whole `UserT` object
Right now the program will encrypt and store the entire UserT object as part of the JWT token passed to the client. Correct this so that only a session identifier, or something like that, is included.

### LINKED ISSUE #11: Use `pipe()` on GremlinImpl and HttpImpl
The Gremlin and HttpImpl classes both have a function called New that needs to be refactored from using the io-ts type's is function to using the pipe() functionality instead. Look at any of the storage layers for examples on how to implement the pipe()

### LINKED ISSUE #128: Data source can be created without a name
## Bug Description
A data source can be created without a name present. This should not be possible

## Steps to Reproduce
Create a data source using either UI or API without a name, it succeeds.

## Impact
We do not want the user to able to create blank named data sources, could cause confusion.

### LINKED ISSUE #144: Event system tests fail sporadically using `npm run test`
## Bug Description
When using `npm run test` the test suite for the event system fails sporadically on line 43. When using an IDE such as Jetbrains, it fails every time.
image

## Steps to Reproduce
Attempt to run tests using `npm run test` a few times, you should see the tests fail on the event system sporadically.

## Impact
Potential problem, but most likely an issue with the mocha test suite vs. our system.

### LINKED ISSUE #152: Move Views under API to a new folder
## Reason
It doesn't make much sense to have views in the API folder.

## Design
A new package location that is more intuitive should be picked.

## Impact
Little impact.

### LINKED ISSUE #153: Consolidate user.ts into container.ts
## Reason

The features currently in users belong to container functionality.
## Design

More or less move the function to the other file.
## Impact

Minimal impact

### LINKED ISSUE #158: Container Users results in 500 error
## Bug Description

When navigating to the Container Users page under Container Administration, a 500 error is returned from the `containers/{containerID}/users` call. The Deep Lynx server shows: `error: row retrieval failed - bind message supplies 6 parameters, but prepared statement "" requires 1`

## Steps to Reproduce

Navigate to the Container Users page under Container Administration. This occurred for a container with no listed users.

### LINKED ISSUE #167: Docker support for Node 13+
## Bug Description
The current Docker implementation does not seem to be able to run Deep Lynx in node 13+ - even though it runs fine outside of Docker.

## Steps to Reproduce
Change the application's Dockerfile to node:13 or above.

## Impact
Currently low impact.

### LINKED ISSUE #172: Data Import: Database transaction not releasing correctly
## Bug Description
The `process` method inside `src/data_processing/processing.ts` is attempting to rollback and/or complete the database transaction passed to it. In reality, the caller of `process` should be in charge of rollbacking/completing database transactions - or the rollback transaction method should stop releasing a client.

## Steps to Reproduce
Attempt to process data, you'll find yourself getting either locking errors or double release errors.

## Impact
High impact, anyone attempting to process data will run into this issue.

### PR DESCRIPTION
**Pull request by DnOberon**
Closes #167, Closes #153, Closes #152, Closes #128, Closes #11, Closes #10 , Closes #9, Closes #8, Closes #172, Closes #158, Closes #144
## Description

- Completely reorganized folder structure across the entire project. Have also renamed various folders above source such as `api_documentation` and `web_ui` to be more user friendly
- Majority of `data_storage` classes converted into `data_mappers`, with most domain complexity, validation, and other operations moved out.
- Created Repositories for the major data/domain objects. The repositories contain all the validation logic as well as allowing the user to communicate with the mappers.
- Subsumed all `filter` classes into the Repositories
- Created multiple new middlewares for the express.js server
- Converted the majority of hard types to domain classes
- Modified tests to include a cleanup step
- Converted Data Source and Exporter repositories into easier to maintain factory/interface pattern

## Motivation and Context
In order to sustain this project over the long term we needed to adopt a different set of design patterns. This was prompted by the upcoming "versioning" feature as well as various discussions regarding project support and longevity.

## How Has This Been Tested?
This has been tested using the testing suite, multiple new tests written and published. There is also a testing checklist at the bottom of this PR that will need to be completed by third parties.

## Types of changes

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [x] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [x] My code follows the code style of this project.
- [x] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.

## Testing Checklist
Here are all the "integration" tests that need to be performed before this pr is ready to go.

- [x] `npm run migrate` on Node 14+ 
- [x] Docker working Node 14+

Perform these tests on the Deep Lynx UI (the user login portion)

- [x] User Login/Logout
- [x] Forgot Password (if you don't set up email for this, you're going to need to manually get the token from the DB and enter it in as a query. I can help or do this myself, so don't stress on doing this one)
- [x] Reset Password functioning
- [x] OAuth Application CRUD 
- [x] KeyPair CRUD (make sure the UI displays the key's secret for you at least once)
- [x] Email Validation

Perform these tests either using the API or the Admin GUI

- [x] CRUD on Metatypes(includes listing with Keys)
- [x] CRUD on Metatype Relationships(includes listing with Keys)
- [x] CRUD on Metatype Keys
- [x] CRUD on Metatype Relationship Keys
- [x] CRUD on Metatype Relationship Pairs
- [x] Container Import & Creation
- [x] Container Invite system
- [x] User Login/Logout
- [x] User OAuth Application Approval
- [x] Event Registration CRUD
- [x] CRUD on Nodes (using graph endpoints)
- [x] CRUD on Edges (using graph endpoints)
- [x] File upload (using data source endpoints)
- [x] HTTP DataSource Polling
- [x] CRUD on Type Mapping / Transformations
- [x] CRUD on Data Exports (using the UI will be the easiest method, I can do the gremlin exporter) 
- [x] Data Source Import Data functioning
- [x] CRUD on Data Source Import's data
- [x] Data Source CRUD

### CODE REVIEW

File: src/data_access_layer/mappers/event_system/event_queue_mapper.ts [hunk 1]
```diff
@@ -0,0 +1,68 @@
...
+
+        return EventQueueMapper.instance
+    }
+
+    public async Retrieve(id: string): Promise<Result<Task>> {
+        // TODO verify it's setting the right values on the included event task
+        return super.retrieve<Task>(this.retrieveStatement(id), {resultClass})
+    }
+
+    public async List(): Promise<Task[]> {
```
Comment (jerenmb) [inline src/data_access_layer/mappers/event_system/event_queue_mapper.ts:36]: Should List() and listStatement() functionality be moved to a repository?

File: src/data_access_layer/mappers/event_system/event_registration_mapper.ts [hunk 2]
```diff
@@ -0,0 +1,167 @@
...
+        if(r.isError) return Promise.resolve(Result.Pass(r))
+
+        return Promise.resolve(Result.Success(r.value[0]))
+    }
+
+    public async Retrieve(id: string): Promise<Result<EventRegistration>> {
+       return super.retrieve(this.retrieveStatement(id), {resultClass: EventRegistration})
+    }
+
+    public async List(): Promise<Result<EventRegistration[]>> {
```
Comment (jerenmb) [inline src/data_access_layer/mappers/event_system/event_registration_mapper.ts:49]: Same comment about List(). How to handle the ListBy* functionality?

File: src/data_access_layer/mappers/mapper.ts [hunk 3]
```diff
@@ -229,3 +290,9 @@ export default class PostgresStorage {
         return uuid.v4()
     }
 }
+
+export type Options<T> = {
```
Comment (jerenmb) [inline src/data_access_layer/mappers/mapper.ts:294]: Maybe add a quick explanation as to why we are including a type here?

File: src/data_access_layer/mappers/data_warehouse/ontology/metatype_relationship_key_mapper.ts [hunk 4]
```diff
@@ -0,0 +1,145 @@
...
+        return super.runStatement(this.archiveStatement(id, userID))
+    }
+
+    // Below are a set of query building functions. So far they're very simple
+    // and the return value is something that the postgres-node driver can understand
+    // My hope is that this method will allow us to be flexible and create more complicated
+    // queries more easily.
+    private createStatement(userID: string, ...keys: MetatypeRelationshipKey[]): string {
+        const text =`INSERT INTO
+                        metatype_relationship_keys(metatype_relationship_id, id, name, description, property_name, required, data_type, options, default_value, validation, created_by, modified_by)
```
[the remark this answers is not in the document]
Comment (DnOberon) [reply src/data_access_layer/mappers/data_warehouse/ontology/metatype_relationship_key_mapper.ts:80]: I'll place them on new lines.

File: src/data_access_layer/mappers/event_system/event_queue_mapper.ts (hunk 1 above)
Comment (DnOberon) [reply src/data_access_layer/mappers/event_system/event_queue_mapper.ts:36]: I think this is one of the few cases where we're not going to do that. We don't work with Task's outside of the mapper so doing a repository just for the listing seems a little too much.

File: src/data_access_layer/mappers/event_system/event_registration_mapper.ts (hunk 2 above)
Comment (DnOberon) [reply src/data_access_layer/mappers/event_system/event_registration_mapper.ts:49]: This I can move to the event registration repository.

File: src/data_access_layer/repositories/data_warehouse/data/edge_repository.ts [hunk 5]
```diff
@@ -0,0 +1,480 @@
...
+                                        this.validateRelationship(edge, transaction)
+                                            .then(valid => {
+                                               if(valid.isError) {
+                                                   resolve(Result.Failure(valid.error?.error!))
+                                                   return
+                                               }
+
+                                               resolve(Result.Success(true))
+                                            })
+                                            .catch(error => resolve(Result.Failure(`unable to relationships for edge${error}`)))
```
Comment (jerenmb) [inline src/data_access_layer/repositories/data_warehouse/data/edge_repository.ts:187]: Update failure message

File: src/data_access_layer/repositories/data_warehouse/data/edge_repository.ts [hunk 6]
```diff
@@ -0,0 +1,480 @@
...
+
+        switch(e.metatypeRelationshipPair!.relationship_type) {
+            // we don't need to check a many:many as we don't have to verify more than whether or not the origin
+            // and destination types match
+            case "many:many": {
+                break;
+            }
+
+            case "one:one": {
+                if(!destinationRelationships.isError && destinationRelationships.value > 0 ) {
```
Comment (jerenmb) [inline src/data_access_layer/repositories/data_warehouse/data/edge_repository.ts:338]: Can you explain why this is > 0 and not > 1?

Comment (DnOberon) [reply src/data_access_layer/repositories/data_warehouse/data/edge_repository.ts:338]: If any current relationship exists between those nodes of the proposed types exist it would violate the `one:one` if we attempted to create a new relationship. Hence checking to see if any already exist. At least, that's the intention.

File: src/data_access_layer/repositories/data_warehouse/data/node_repository.ts [hunk 7]
```diff
@@ -0,0 +1,319 @@
...
+
+    property(key: string, operator: string, value: any) {
+        super.queryJsonb(key, "nodes.properties", operator, value)
+        return this
+    }
+
+    async count(): Promise<Result<number>> {
+        const results = await super.count()
+        // reset the query
+        this._rawQuery = [
```
[the remark this answers is not in the document]
Comment (DnOberon) [reply src/data_access_layer/repositories/data_warehouse/data/node_repository.ts:281]: The `rawQuery` is reset each time `count` or `list` is called by the parent class. The default value of the `rawQuery` is simply a `SELECT * FROM {tablename}` statement. While that works for the majority of cases, we must include additional SELECT parameters, or JOIN statements for certain data types that require data from other tables.

File: src/data_access_layer/repositories/data_warehouse/import/data_staging_repository.ts [hunk 8]
```diff
@@ -0,0 +1,201 @@
...
+    }
+
+    findByID(id: number, transaction?: PoolClient): Promise<Result<DataStaging>> {
+        return this.#mapper.Retrieve(id, transaction)
+    }
+
+    async save(record: DataStaging, user?: User, transaction?: PoolClient): Promise<Result<boolean>> {
+        let internalTransaction: boolean = false
+        const errors = await record.validationErrors()
+        if(errors) return Promise.resolve(Result.Failure(`node does not pass validation ${errors.join(",")}`))
```
Comment (jerenmb) [inline src/data_access_layer/repositories/data_warehouse/import/data_staging_repository.ts:34]: Does the failure log need to be updated from node to "data staging"?

File: src/data_access_layer/repositories/data_warehouse/import/import_repository.ts [hunk 9]
```diff
@@ -0,0 +1,120 @@
...
+    findByIDAndLock(id: string, transaction: PoolClient): Promise<Result<Import>> {
+        return this.#mapper.RetrieveAndLock(id,transaction)
+    }
+
+    // locking is only done in the context of a transaction, so one must be included
+    findLastAndLock(dataSourceID: string, transaction: PoolClient): Promise<Result<Import>> {
+        return this.#mapper.RetrieveLastAndLock(dataSourceID, transaction)
+    }
+
+    // locking is only done in the context of a transaction, so one must be included
```
Comment (jerenmb) [inline src/data_access_layer/repositories/data_warehouse/import/import_repository.ts:38]: Remove or alter this comment?

File: src/data_access_layer/repositories/event_system/event_registration_repository.ts [hunk 10]
```diff
@@ -0,0 +1,86 @@
...
+/*
+    EventRegistrationRepository contains methods for persisting and retrieving an event registration
+    to storage. Users should interact with repositories when possible and not
+    the mappers as the repositories contain additional logic such as validation
+    or transformation prior to storage or returning. This is not used to actually
+    emit events, only manage registrations.
+ */
+export default class EventRegistrationRepository extends Repository implements RepositoryInterface<EventRegistration> {
+    #mapper: EventRegistrationMapper = EventRegistrationMapper.Instance
+    delete(e: EventRegistration): Promise<Result<boolean>> {
```
Comment (jerenmb) [inline src/data_access_layer/repositories/event_system/event_registration_repository.ts:17]: Insert space here

File: src/data_warehouse/data/edge.ts [hunk 11]
```diff
@@ -0,0 +1,153 @@
...
+    id?: string
+
+    @IsUUID()
+    container_id?: string
+
+    @IsOptional()
+    @IsBoolean()
+    archived?: boolean
+
+    // we often need the metatype's name, it's keys, or access to other properties
```
Comment (jerenmb) [inline src/data_warehouse/data/edge.ts:24]: Update comment to reflect metatype relationship pairs and edges?

File: src/data_warehouse/data/edge.ts [hunk 12]
```diff
@@ -0,0 +1,153 @@
...
+
+    // if we have an composite id, we must provide a data source as we can only
+    // guarantee uniqueness based on that combination of values
+    @ValidateIf(o =>  typeof o.composite_original_id !== "undefined" && o.composite_original_id !== null)
+    @IsUUID()
+    data_source_id?: string
+
+    @IsUUID()
+    @IsOptional()
+    type_mapping_transformation_id?: string // TODO: fetch the full type mapping object
```
Comment (jerenmb) [inline src/data_warehouse/data/edge.ts:69]: Should this TODO be resolved before PR completion?

File: src/data_warehouse/import/import.ts [hunk 13]
```diff
@@ -0,0 +1,104 @@
...
+
+    @IsUUID()
+    data_source_id?: string
+
+    @IsOptional()
+    @IsString()
+    status_message?: string
+
+    @IsString()
+    status: "ready" | "processing" | "error" | "stopped" | "completed" = "ready"
```
Comment (jerenmb) [inline src/data_warehouse/import/import.ts:22]: Reason for not using @IsIn?

File: src/data_warehouse/data/edge.ts (hunk 12 above)
Comment (DnOberon) [reply src/data_warehouse/data/edge.ts:69]: Decided this was not a good idea. Went ahead and removed it.

File: src/data_warehouse/import/import.ts (hunk 13 above)
Comment (DnOberon) [reply src/data_warehouse/import/import.ts:22]: In this case the data type is an actual ENUM on the backend. Since we rely heavily on the actual type name, and not so much as a "supported" value type thing, I decided to keep this as it was originally.

File: src/data_access_layer/repositories/data_warehouse/etl/type_mapping_repository.ts [hunk 14]
```diff
@@ -0,0 +1,373 @@
...
+                await this.#mapper.rollbackTransaction(transaction)
+                return Promise.resolve(Result.Failure(`unable to commit changes to database ${committed.error}`))
+            }
+        }
+
+        return Promise.resolve(Result.Success(true))
+    }
+
+    // this is how users should be managing a type mapping's transformations - not
+    // through the opposite repository if possible.
```
[the remark this answers is not in the document]
Comment (DnOberon) [reply src/data_access_layer/repositories/data_warehouse/etl/type_mapping_repository.ts]: changed it to read the "type transformation repository"

**Review by jerenmb — APPROVED** [review]
Approved
